### ISSUE TITLE
Call to undefined function get_available_post_statuses() in includes/form.php:124

### ISSUE THREAD

**Issue by sokai** [tombenj/advanced-random-posts-widget#2]
## Error

_(adjusted for privacy reasons)_

```php
2021/08/23 12:46:45 [error] 26565#26565: *2304245 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function get_available_post_statuses() in /$my_path/wp-content/plugins/advanced-random-posts-widget/includes/form.php:124
Stack trace:
#0 /$my_path/wp-content/plugins/advanced-random-posts-widget/includes/widget.php(141): include()
#1 /$my_path/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(545): Advanced_Random_Posts_Widget->form()
#2 /$my_path/wp-includes/rest-api/endpoints/class-wp-rest-widget-types-controller.php(484): WP_REST_Widget_Types_Controller->get_widget_form()
#3 /$my_path/wp-includes/rest-api/class-wp-rest-server.php(1140): WP_REST_Widget_Types_Controller->encode_form_data()
#4 /$my_path/wp-includes/rest-api/class-wp-rest-server.php(987): WP_REST_Server->respond_to_request()
#5 /$my_path/wp-includes/rest-api/" while reading response header from upstream, client:  0.0.0.0, server: my.doma.in, request: "POST /wp-json/wp/v2/widget-types/arpw-widget/encode?_locale=user HTTP/2.0", upstream: "fastcgi://unix:/var/run/1-user-my.doma.in-php-fpm.socket:", host: "my.doma.in", referrer: "https://my.doma.in/wp-admin/widgets.php"
```

## File

https://github.com/satrya/advanced-random-posts-widget/blob/df938191ad41ac71b8377f8332f8f4303c460137/includes/form.php#L124

## Fix

```php
foreach ( array_keys( get_object_vars( wp_count_posts( 'post' ) ) ) as $status_value => $status_label ) {
```

@satrya I'll create a PR (and hope you can + will fix it for us) :-)

KR

**Comment by sokai** [comment]
@satrya Is there something I can do to get this issue fixed by merging PR #3? KR!
